product/urls.py
from django.urls import path
from product.views import main_view, product_view, products_view, product_list_view, shopping_list_view, Shoppinglist

urlpatterns = [
    path("", main_view),
    path("product/", products_view),
    path("product/<int:resource_id>", product_view),
    path("product_list/", product_list_view),
    path("shopping_list/", shopping_list_view),
    path('shopping_list_api/', Shoppinglist.as_view()),
    path('shopping_list_api/<int:resource_id>', Shoppinglist.as_view()),
]

shoppinglist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("product.urls"))
]

product/models.py
from django.db import models
from datetime import datetime
from django_resized import ResizedImageField

class Product(models.Model):
    id = models.BigAutoField(primary_key=True, editable=False)
    created_at = models.DateTimeField(default=datetime.utcnow)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    image = ResizedImageField(size=[300, 300], upload_to='static/product_images/', blank=True, null=True, default=None)
    category = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class ShoppingItem(models.Model):
    id = models.BigAutoField(primary_key=True, editable=False)
    created_at = models.DateTimeField(default=datetime.utcnow)
    product_name = models.ForeignKey(Product, on_delete=models.CASCADE)
    location = models.CharField(max_length=100, default=None)
    price = models.FloatField(blank=True, null=True, default=None)
    amount = models.IntegerField(blank=True, null=True, default=1)

    def __str__(self):
        return str(self.id)

product/forms/product_form.py
from django import forms
from ..models import Product
from django.core.exceptions import ValidationError
from PIL import Image

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ("name", "description", "category", "image")
        exclude = ("created_at", "id")

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)

product/views.py
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.shortcuts import render
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from product.forms.product_form import ProductForm
from product.models import Product, ShoppingItem
from product.serializers import ShoppingItemSerializer
from django.forms.models import model_to_dict


def product_list_view(request):
    template_path = "product_list.html"
    context_dict = {}
    all_products = Product.objects.all()
    context_dict["data"] = all_products
    return render(request, template_path, context_dict)


def product_view(request, resource_id=None):
    context_dict = {}
    template_path = "product.html"
    if resource_id and request.method == 'GET':
        product = Product.objects.filter(id=resource_id).first()
        product_data = model_to_dict(product) if product else None
        product_form = ProductForm(product_data)
        if product_form.is_valid():
            context_dict["form"] = product_form
            return render(request, template_path, context_dict)
    if request.method == 'DELETE':
        product = Product.objects.get(id=resource_id)
        product.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
    if request.method == 'POST' and resource_id:
        product = Product.objects.filter(id=resource_id).first()
        data = request.POST
        product.name = data["name"]
        product.description = data["description"]
        product.category = data["category"]
        if request.FILES:
            product.image = request.FILES["image"]
        product.save()
        messages.success(request, "Created a new product")
        return HttpResponseRedirect("/product_list/")


def products_view(request):
    template_path = "product.html"
    context_dict = {}
    data = request.POST
    if request.FILES:
        product_form = ProductForm(data, request.FILES)
    else:
        product_form = ProductForm(data or None)
    if request.method == 'GET':
        context_dict["form"] = product_form
        return render(request, template_path, context_dict)
    if request.method == 'POST':
        if product_form.is_valid():
            product = product_form.save(commit=False)
            product.save()
            messages.success(request, "Created a new product")
        return HttpResponseRedirect("/product_list/")


class Shoppinglist(APIView):
    def get(self, request, resource_id=None):
        if resource_id:
            item = ShoppingItem.objects.prefetch_related('product_name').filter(id=resource_id).first()
            serializer = ShoppingItemSerializer(item)
            return Response(serializer.data, status=status.HTTP_200_OK)

        items = ShoppingItem.objects.all()
        serializer = ShoppingItemSerializer(items, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)

    def post(self, request):
        data = request.data
        if "product_id" in data:
            product_object = Product.objects.filter(id=data["product_id"]).first()
        else:
            product_object = Product.objects.filter(name=data["product"]).first()
        item = ShoppingItem()
        item.product_name = product_object
        item.location = data["location"] if "location" in data else ""
        item.price = float(data["price"]) if "price" in data else None
        item.amount = int(data["amount"]) if "amount" in data else 1
        item.save()
        return Response({"id": item.id}, status=status.HTTP_201_CREATED)

    def delete(self, request, resource_id):
        shopping_item = ShoppingItem.objects.get(id=resource_id)
        shopping_item.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

def shopping_list_view(request):
    template_path = "shopping_list.html"
    context_dict = {}
    if request.method == 'GET':
        all_items = ShoppingItem.objects.prefetch_related('product_name').all()
        all_products = Product.objects.values_list("name", flat=True)
        context_dict["shopping_items"] = all_items
        context_dict["products"] = all_products
        return render(request, template_path, context_dict)


def main_view(request):
    return render(request, "main.html", {})

templates/footer.html
    <footer>
        <p>&copy; 2024 Shopping list. All rights reserved.</p>
    </footer>
</body>
</html>

templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="/static/script.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <link rel="stylesheet" href="/static/style.css">
    <title>Shopping list</title>
</head>
<body>
    <header>
        <div class="topnav" id="id_topnav">
            <a href="/" class="active">Home</a>
            <a href="/product/">Add product</a>
            <a href="/product_list/">Product list</a>
            <a href="/shopping_list/">Shopping list</a>
            <a href="javascript:void(0);" class="icon" onclick="addResponsiveClass()"></a>
        </div>
    </header>

templates/main.html
{% include 'header.html' %}
<div class="center-content content">
     <p>Welcome to Your Digital Shopping Assistant</p>
     <button onclick="window.location.href='/product/';">Create product</button>
     <button onclick="window.location.href='/shopping_list/';">Shopping list</button>
     <button onclick="window.location.href='/product_list/';">Products list</button>
</div>
{% include 'footer.html' %}

templates/product.html
{% include 'header.html' %}
<div class="content center-content">
    <p>Product Information</p>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="button" type="submit" value="Save">
    </form>
 </div>
{% include 'footer.html' %}

templates/product_list.html
{% include 'header.html' %}
<div class="content">
    {% csrf_token %}
    <div class="grid-container">
        {% for item in data %}
            <div class="border-list">
                {% if item.image %}
                    <img class="product-image" src="{{ item.image.url }}" alt="Product Image">
                {% else %}
                    <div class="product-image"></div>
                {% endif %}
                <div class="add-list" product-id="{{ item.id }}">
                    <span class="material-icons plus-product" onclick="addProductToShoppingList({{ item.id }})">add</span>
                    <span class="material-symbols-outlined loading-icon" style="display: none;">directory_sync</span>
                </div>
                <div class="product-details">
                    <div><span>Product: </span>{{ item.name }}</div>
                    <div><span>Description: </span>{{ item.description }}</div>
                    <div><span>Category: </span>{{ item.category }}</div>
                </div>

                <div class="product-actions">
                    <button onclick="editProduct({{ item.id }})">Edit</button>
                    <button onclick="deleteProduct({{ item.id }})">Delete</button>
                </div>

            </div>
        {% endfor %}
    </div>
</div>
{% include 'footer.html' %}

templates/shopping_list.html
{% include 'header.html' %}
<div class="center-content content">
    {% csrf_token %}
    <div id="id_shopping_list" class="form">
        {% for item in shopping_items %}
            <div class="item-row">
                {% if item.product_name.image %}
                    <img class="product-image" src="{{ item.product_name.image.url }}" alt="Product Image">
                {% endif %}
                <span>{{ forloop.counter }}. </span>
                {% if item.amount and item.amount > 1 %}
                    <div style="padding-left: 10px;"><span>Amount: </span>{{ item.amount }}</div>
                {% endif %}
                <div><span></span>{{ item.product_name.name }} - {{ item.product_name.description }} </div>
                {% if item.location %}
                    <div style="padding-left: 10px;"><span>Location: </span>{{ item.location }}</div>
                {% endif %}
                {% if item.price %}
                    <div style="padding-left: 10px;"><span>Price: </span>{{ item.price }}</div>
                {% endif %}
                <span class="material-icons" style="margin-left: 5px; color: red; cursor: pointer;" onclick="deleteShoppingItem({{ item.id }});">clear</span>
            </div>
        {% endfor %}
    </div>
    <div style="width: 300px; margin-left: 40%;">
        <select id="id_selected_product" name="product_name">
            {% for name in products %}
                <option value="{{ name }}">{{ name }}</option>
            {% endfor %}
        </select>
        <input type="text" name="amount" id="id_amount" placeholder="Amount">
        <input type="text" name="price" id="id_price" placeholder="Price">
        <input type="text" name="location" id="id_location" placeholder="Location">
    </div>
    <button class="button-shopping" onclick="addShoppingItem()">Add</button>
</div>
{% include 'footer.html' %}